# Generated by Django 4.2.19 on 2025-04-02 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField(help_text='Use o formato 00/00/0000', max_length=8, validators=[django.core.validators.RegexValidator(message='Data de nascimento inválida. Use o formato 00/00/0000', regex='^\\d{2}/\\d{2}/\\d{4}$')])),
                ('telefone', models.CharField(help_text='Use o formato (00) 00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (00) 00000-0000', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
            ],
        ),
    ]
