# Generated by Django 4.2.20 on 2025-04-02 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alunos_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateField(help_text='Use o formato 00/00/0000', max_length=8, validators=[django.core.validators.RegexValidator(message='Data de nascimento inválida. Use o formato 00/00/0000', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
