# Generated by Django 4.2.20 on 2025-04-02 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_alunos_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateTimeField(help_text='Use o formato 00/00/0000 (Dia-Mês-Ano)', max_length=8, validators=[django.core.validators.RegexValidator(message='Data de nascimento inválida. Use o formato 00/00/0000 (Dia-Mês-Ano)', regex='^\\d{2}/\\d{2}/\\d{4}$')]),
        ),
    ]
