# Generated by Django 4.2.20 on 2025-04-02 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_alunos_data_de_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateField(help_text='Use o formato 0000-00-00 (Ano-Mês-Dia)', validators=[django.core.validators.RegexValidator(message='Data de nascimento inválida. Use o formato 0000-00-00 (Ano-Mês-Dia)')]),
        ),
    ]
