# Generated by Django 4.2.20 on 2025-04-03 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_remove_alunos_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='alunos',
            name='endereco_cep',
            field=models.CharField(default=0, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', message='Use o formato 00000-000')], verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateField(help_text='Use o formato 0000-00-00 (Ano-Mês-Dia)', validators=[django.core.validators.RegexValidator(message='Data de nascimento inválida. Use o formato 0000-00-00 (Ano-Mês-Dia)')], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Aluno'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='telefone',
            field=models.CharField(help_text='Use o formato (00) 00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (00) 00000-0000', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
