# Generated by Django 4.2.20 on 2025-04-03 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_alunos_options_alunos_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='endereco_cep',
            field=models.CharField(help_text='Use o formato 00000-000', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', message='Cep inválido. Use o formato 00000-000')], verbose_name='CEP'),
        ),
    ]
