# Generated by Django 4.2.20 on 2025-04-19 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_alunos_cpf_alunos_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(default=None, help_text='Use o formato 000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator('^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$', message='CPF inválido. Use o formato 000.000.000-00')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(default=None, help_text='Use o formato email@email.com', max_length=255, validators=[django.core.validators.RegexValidator(message='Email inválido. Use o formato email@email.com')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='telefone',
            field=models.CharField(default=None, help_text='Use o formato (00) 00000-0000', max_length=15, validators=[django.core.validators.RegexValidator('^\\(?\\d{2}\\)?\\s?\\d{5}-?\\d{4}$', message='Telefone inválido. Use o formato (00) 00000-0000')], verbose_name='Telefone'),
        ),
    ]
