# Generated by Django 4.2.20 on 2025-04-19 21:40

import alunos.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_alunos_cpf_alter_alunos_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(default=None, help_text='Digite o CPF sem pontos ou traços, exemplo: 82178537464', max_length=11, unique=True, validators=[alunos.utils.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateField(default=None, help_text='Selecione sua data de nascimento.', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='endereco_cep',
            field=models.CharField(default=None, help_text='Digite o CEP sem traços, exemplo: 12345678', max_length=8, validators=[alunos.utils.validar_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='telefone',
            field=models.CharField(default=None, help_text='Digite o telefone sem parênteses ou traços, exemplo: 11994029275', max_length=11, validators=[alunos.utils.validar_telefone], verbose_name='Telefone'),
        ),
    ]
