# Generated by Django 4.2.20 on 2025-04-19 21:41

import alunos.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_alter_alunos_cpf_alter_alunos_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(default=None, help_text='Use o formato email@email.com', max_length=255, validators=[alunos.utils.validar_email], verbose_name='Email'),
        ),
    ]
