# Generated by Django 4.2.20 on 2025-04-25 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_alter_alunos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nome Inválido.', regex='[a-zA-Z]')], verbose_name='Nome do Aluno'),
        ),
    ]
