# Generated by Django 4.2.20 on 2025-05-05 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_alter_alunos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(help_text='Deve conter nome e sobrenome (sem caracteres árabes).', max_length=255, validators=[django.core.validators.RegexValidator(message='Nome inválido. Deve conter nome e sobrenome (sem caracteres árabes).', regex='^(?!.*[\\u0600-\\u06FF])\\s*([a-zA-ZÀ-ÿ]+[\\s]+)+[a-zA-ZÀ-ÿ]+\\s*$')], verbose_name='Nome do Aluno'),
        ),
    ]
