# Generated by Django 4.2.20 on 2025-04-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0007_alter_alunos_options_alunos_endereco_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_matricula', models.DateTimeField(auto_now_add=True)),
                ('tempo_de_plano', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', help_text='Escolha seu plano.', max_length=255, verbose_name='Plano')),
                ('status_da_matricula', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='inativo', help_text='Status do plano.', max_length=255, verbose_name='Status da Matrícula')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='alunos.alunos')),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
