# Generated by Django 4.2.20 on 2025-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='status_da_matricula',
            field=models.CharField(blank=True, help_text='Status da matrícula do aluno.', max_length=255, null=True, verbose_name='Status da Matrícula'),
        ),
    ]
