# Generated by Django 4.2.20 on 2025-04-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_matriculas_status_da_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='tempo_de_plano',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='tempo_restante_de_matricula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='tipo_de_plano',
            field=models.IntegerField(choices=[('30', 'Mensal'), ('90', 'Trimestral'), ('180', 'Semestral'), ('365', 'Anual')], default='30', help_text='Escolha seu plano.', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='status_da_matricula',
            field=models.CharField(blank=True, default='Inativo', max_length=255, null=True, verbose_name='Status da Matrícula'),
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Preço')),
                ('status_pagamento', models.CharField(blank=True, default='Pendente', max_length=255, null=True, verbose_name='Status do Pagamento')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='matriculas.matriculas')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
