# Generated by Django 4.2.20 on 2025-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_matricula_pagamento_remove_pagamentos_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='plano',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='plano_efi_id'),
        ),
    ]
