# Generated by Django 4.2.20 on 2025-04-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_alter_matricula_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='preco',
            new_name='tipo_do_plano',
        ),
    ]
