# Generated by Django 4.2.20 on 2025-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_rename_preco_matricula_tipo_do_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status_da_matricula',
            field=models.CharField(blank=True, default='inativa', max_length=255, null=True, verbose_name='status da matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_do_plano',
            field=models.IntegerField(choices=[(30, 'Mensal - 30 dias (R$ 40,00)'), (90, 'Trimestral - 90 dias (R$ 60,00)'), (180, 'Semestral - 180 dias (R$ 99,00)'), (365, 'Anual - 365 dias (R$ 120,00)')], default=30, help_text='Escolha seu plano.', verbose_name='plano'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='assinatura',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='assinatura_efi_id'),
        ),
    ]
