# Generated by Django 4.2.20 on 2025-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_alter_matricula_status_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status_da_matricula',
            field=models.CharField(blank=True, default='Inativa', max_length=255, null=True, verbose_name='status da matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_do_plano',
            field=models.IntegerField(choices=[(90, 'Trimestral - 90 dias (R$ 60,00)'), (180, 'Semestral - 180 dias (R$ 99,00)'), (365, 'Anual - 365 dias (R$ 120,00)')], default=90, help_text='Escolha seu plano.', verbose_name='plano'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status_do_pagamento',
            field=models.CharField(blank=True, default='Pendente', max_length=255, null=True, verbose_name='status do pagamento'),
        ),
    ]
