# Generated by Django 4.2.20 on 2025-04-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_alter_matricula_status_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='status_do_pagamento',
        ),
        migrations.CreateModel(
            name='GerarPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.IntegerField(blank=True, default=None, null=True, verbose_name='assinatura_efi_id')),
                ('status_do_pagamento', models.CharField(blank=True, default='Pendente', max_length=255, null=True, verbose_name='status do pagamento')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerar_pagamento', to='matriculas.matricula')),
            ],
            options={
                'verbose_name_plural': 'Pagamento',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pagamento',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='matriculas.gerarpagamento'),
        ),
    ]
