# Generated by Django 4.2.20 on 2025-04-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_alter_pagamento_options_remove_pagamento_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerarpagamento',
            options={'verbose_name_plural': 'Gerar Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name_plural': 'Pagamento'},
        ),
    ]
