# Generated by Django 4.2.20 on 2025-04-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_alter_gerarpagamento_options_alter_pagamento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerarpagamento',
            name='status_do_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status_do_pagamento',
            field=models.CharField(blank=True, default='Pendente', max_length=255, null=True, verbose_name='status do pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='matriculas.gerarpagamento'),
        ),
    ]
