# Generated by Django 4.2.20 on 2025-04-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_remove_gerarpagamento_status_do_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelarMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelamentos', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancelamento', to='matriculas.matricula')),
            ],
            options={
                'verbose_name_plural': 'Cancelamento de Matrícula',
            },
        ),
    ]
