# Generated by Django 4.2.20 on 2025-04-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0014_rename_cancelamentos_cancelarmatricula_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cancelamento_da_matricula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancelarmatricula',
            name='cancelamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamento', to='matriculas.matricula'),
        ),
    ]
