# Generated by Django 4.2.20 on 2025-04-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0015_matricula_cancelamento_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status_da_matricula',
            field=models.BooleanField(default=False),
        ),
    ]
