# Generated by Django 4.2.20 on 2025-04-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_alter_alunos_email'),
        ('matriculas', '0016_alter_matricula_status_da_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='alunos.alunos'),
        ),
    ]
