# Generated by Django 4.2.20 on 2025-04-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_alter_alunos_email'),
        ('matriculas', '0017_alter_matricula_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='alunos.alunos'),
        ),
    ]
