# Generated by Django 4.2.20 on 2025-04-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0019_alter_matricula_cancelamento_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='matriculas.matricula'),
        ),
    ]
