# Generated by Django 4.2.20 on 2025-04-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0020_alter_pagamento_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelarmatricula',
            name='cancelamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamento', to='matriculas.matricula'),
        ),
    ]
