# Generated by Django 4.2.20 on 2025-04-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0021_alter_cancelarmatricula_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_do_pagamento',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
