# Generated by Django 4.2.20 on 2025-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0022_pagamento_data_do_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='cancelamento_da_matricula',
        ),
        migrations.AddField(
            model_name='cancelarmatricula',
            name='data_do_cancelamento',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
