# Generated by Django 4.2.20 on 2025-04-25 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0023_remove_matricula_cancelamento_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='assinatura',
            field=models.IntegerField(blank=True, default=None, verbose_name='assinatura_efi_id'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_da_matricula',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
