# Generated by Django 4.2.20 on 2025-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0024_alter_matricula_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='plano',
            field=models.IntegerField(blank=True, default=None, verbose_name='plano_efi_id'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo_do_pagamento',
            field=models.CharField(choices=[('credit_card', 'Cartão De Crédito'), ('banking_billet', 'Boleto Bancário')], default='credit_card', help_text='Escolha o método de pagamento.', max_length=255, verbose_name='metodo do pagamento'),
        ),
    ]
