# Generated by Django 4.2.20 on 2025-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0025_matricula_plano_pagamento_metodo_do_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_da_matricula',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_do_pagamento',
            field=models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('banking_billet', 'Boleto Bancário')], default='credit_card', help_text='Escolha o método de pagamento.', max_length=255, verbose_name='metodo do pagamento'),
        ),
    ]
