# Generated by Django 4.2.20 on 2025-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0026_alter_matricula_data_da_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status_do_pagamento',
            field=models.CharField(choices=[('pendente', 'Pagamento Pendente'), ('aprovado', 'Pagamento Aprovado'), ('recusado', 'Pagamento Recusado'), ('estornado', 'Pagamento Estornado'), ('reembolsado', 'Pagamento Reembolsado')], default='pendente', help_text='Status do pagamento.', max_length=255, verbose_name='status do pagamento'),
        ),
    ]
